services:
  postgres:
    image: postgres:16
    environment:
      - DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - DATABASE_USER=${POSTGRES_DATABASE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}